apiVersion: apps/v1            # Version API Kubernetes
kind: Deployment
metadata:
  name: python-app-deployment    # Nom du déploiement
spec:                        # spécification du déploiement
  replicas: 3                    # Nombres de répliques du déploiement
  selector:
    matchLabels:
      app: python-app            # Etiquettes et valeur qui doivent être associés aux PODs de ce déploiement
  template:
    metadata:
      labels:
        app: python-app          # Etiquettes et valeur associés aux PODs générés
    spec:                    # spécification du POD
      imagePullSecrets:
      - name: regcred        # Mes credentials pour le HubDocker
      containers:
      - name: python_app                    # Nom du conteneur
        image: xavnono/python_app:latest    # Image Docker utilisée
        ports:
        - containerPort: 8900              # Port d'écoute du conteneur

