apiVersion: apps/v1            # Version API Kubernetes
kind: Deployment
metadata:
  name: python_app_deployment    # Nom du déploiement
spec:                        # spécification du déploiement
  replicas: 3                    # Nombres de répliques du déploiement
  selector:
    matchLabels:
      app: python_app            # Etiquettes et valeur qui doivent être associés aux PODs de ce déploiement
  template:
    metadata:
      labels:
        app: python_app          # Etiquettes et valeur associés aux PODs générés
    spec:                    # spécification du POD
      containers:
      - name: python_app                    # Nom du conteneur
        image: xavnono/python_app:latest    # Image Docker utilisée
        ports:
        - containerPort: 8900              # Port d'écoute du conteneur
        imagePullSecrets:
        - name: regcred
