apiVersion: apps/v1
kind: Deployment
metadata:
  name: mypythonapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mypythonapp
  template:
    metadata:
      labels:
        app: mypythonapp
    spec:
      containers:
      - name: mypythonapp
        image: xavnono/mypythonapp:tagname
        ports:
        - containerPort: 80