version: '3'
services:
  mypythonapp:
    image: xavnono/mypythonapp:latest
    ports:
      - "8089:8089"
  scout:
    image: scoutapp/scoutapm
    depends_on:
      - mypythonapp
    command: "scout mypythonapp:8089"