version: '3'

services:
  scout-cli:
    image: docker/scout-cli
    ports: 
      - "11434:11434"
    command: >
      sh -c '
        echo $DOCKER_HUB_PAT | docker login -u $DOCKER_HUB_USER --password-stdin &&
        docker-scout cves $IMAGE_TAG --exit-code --only-severity critical,high'
