version: '3'
services:
  python_app_test:
    image: xavnono/python_app:latest
    ports:
      - "8000:8888"
  scout_test:
    image: scout-cli:latest
    depends_on:
      - python_app_test
    command: "scout python_app_test:8888"