version: '3.8'
services:
  mypythonapp:
    image: xavnono/mypythonapp:latest
    ports:
      - "8089:8089"
  scout:
    image: docker/scout-cli:latest
    depends_on:
      - mypythonapp
    command: "docker scout mypythonapp:8089"