version: '3'

services:
  scout-cli:
    image: docker/scout-cli
    environment:
      - DOCKER_SCOUT_HUB_USER=${DOCKER_HUB_USER}
      - DOCKER_SCOUT_HUB_PASSWORD=${DOCKER_HUB_PAT}
    command: cves xavnono/python-app --exit-code --only-severity critical,high

project: tp4
