version: '3'
services:
  python_app:
    image: xavnono/python_app:latest
    ports:
      - "8000:8888"
  scout_test:
    image: scoutapp/docker-scout
    depends_on:
      - python_app
    command: "scout python_app:8888"