version: '3'

services:
  scout-cli:
    image: docker/scout-cli
    environment:
      - DOCKER_SCOUT_HUB_USER=xavnono
      - DOCKER_SCOUT_HUB_PASSWORD=dckr_pat_4J2oyGlyWzsg8HafBxz4YnTOqhQ
    command: cves xavnono/python_app --exit-code --only-severity critical,high

  # python_app:
  #   image: xavnono/python_app
