apiVersion: v1
kind: Service
metadata:
  name: service # Nom du Service Kubernetes à créer dans le cluster
spec: 
  selector:
    app: python-app 
  type: LoadBalancer # Type de Service Kubernetes
  ports:
  - protocol: TCP
    port: 8900 # Service port
    targetPort: 8900 # Le port pour l'application python-app